USE sistemadelocalidades;

# 1
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. APENAS NAS CIDADES QUE TEM ESTADO

SELECT CIDADE.Nome AS Cidade, ESTADO.Uf AS UF
FROM CIDADE
INNER JOIN ESTADO ON Cidade.Estado_ID = ESTADO.ID;
 
# 2
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. TODAS AS CIDADES, INDEPENDENTE DE TEREM ESTADO

SELECT CIDADE.Nome AS Cidade, ESTADO.Uf AS UF
FROM CIDADE
LEFT JOIN  ESTADO ON CIDADE.Estado_ID = ESTADO.ID;

# 3
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. MOSTRE TODOS OS ESTADOS, INDEPENDENTE DE TEREM CIDADES

SELECT CIDADE.Nome AS Cidade, ESTADO.Uf AS UF, ESTADO.Nome AS Estado
FROM CIDADE
RIGHT JOIN ESTADO ON CIDADE.Estado_ID = ESTADO.ID;
 
# 4
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE, ESTADO E PREFEITO:
-- CIDADE.NOME, ESTADO.SIGLA/UF, PREFEITO.NOME, PREFEITO.DATAPOSSE
-- PARA TODAS AS CIDADES QUE TEM PREFEITO

SELECT CIDADE.Nome AS Cidade, ESTADO.Uf AS UF, PREFEITO.DataPosse AS DataPosse, PREFEITO.Nome AS Prefeito
FROM CIDADE
LEFT JOIN ESTADO ON CIDADE.ESTADO_ID = ESTADO.ID
INNER JOIN PREFEITO ON CIDADE.PREFEITO_ID = PREFEITO.ID;
